app = "pd-bifrost"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_HOST = "0.0.0.0"
  APP_DIR = "/app/data"

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0

[[mounts]]
  source = "data"
  destination = "/app/data"

