app = "pd-bifrost"
primary_region = "sin"

[deploy]
  ha = false

[build]
  dockerfile = "Dockerfile"

[env]
  APP_HOST = "0.0.0.0"
  APP_DIR = "/app/data"

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 512

[[mounts]]
  source = "data"
  destination = "/app/data"

